import CommandLayout from '../../components/CommandLayout';
import { Card, Field } from '../../components/UiBits';
import { exportState, useCommandCenter } from '../../lib/commandCenterStore';

export default function Profile(){
 const { state, update, resetAll } = useCommandCenter();
 const p = state.profile;
 const set=(k,v)=>update('profile',{...p,[k]:v});
 const importData=(e)=>{ const f=e.target.files?.[0]; if(!f) return; const r=new FileReader(); r.onload=()=>{ try { const parsed=JSON.parse(r.result); update('profile', parsed.profile || p); } catch {} }; r.readAsText(f); };
 return <CommandLayout title="Profile / Settings"><Card><div className="grid md:grid-cols-2 gap-2"><Field label="Name" value={p.name} onChange={(e)=>set('name',e.target.value)}/><Field label="Age" type="number" value={p.age} onChange={(e)=>set('age',Number(e.target.value)||0)}/><Field label="Current job" value={p.currentJob} onChange={(e)=>set('currentJob',e.target.value)}/><Field label="Main mission" value={p.mainMission} onChange={(e)=>set('mainMission',e.target.value)}/><Field label="Current weight" type="number" value={p.currentWeight} onChange={(e)=>set('currentWeight',Number(e.target.value)||0)}/><Field label="Goal weight" type="number" value={p.goalWeight} onChange={(e)=>set('goalWeight',Number(e.target.value)||0)}/><Field label="Monthly income goal" type="number" value={p.monthlyIncomeGoal} onChange={(e)=>set('monthlyIncomeGoal',Number(e.target.value)||0)}/><Field label="Annual income goal" type="number" value={p.annualIncomeGoal} onChange={(e)=>set('annualIncomeGoal',Number(e.target.value)||0)}/><Field label="Main business niche" value={p.mainBusinessNiche} onChange={(e)=>set('mainBusinessNiche',e.target.value)}/><Field label="Top 3 life values" value={p.topValues} onChange={(e)=>set('topValues',e.target.value)}/><Field label="2-year vision" value={p.vision2} onChange={(e)=>set('vision2',e.target.value)}/><Field label="5-year vision" value={p.vision5} onChange={(e)=>set('vision5',e.target.value)}/><Field label="10-year vision" value={p.vision10} onChange={(e)=>set('vision10',e.target.value)}/><Field label="20-year vision" value={p.vision20} onChange={(e)=>set('vision20',e.target.value)}/></div><div className="flex gap-2 mt-4 flex-wrap"><button className="btn-secondary" onClick={()=>exportState(state)}>Export Data</button><label className="btn-secondary cursor-pointer">Import Data<input type="file" accept="application/json" className="hidden" onChange={importData}/></label><button className="btn-secondary" onClick={()=>{ if(confirm('Reset all app data?')) resetAll(); }}>Reset Data</button></div></Card></CommandLayout>
}
